In [1]:
import numpy as np
import scipy.linalg as sc

A = np.array([[1,2,3],[2,16,21],[4,28,73]])
P, L, U = sc.lu(A)

print(P)
print(L)
print(U)

print(np.dot(P, A) - np.dot(L,U))

print("A = L*U")
print(np.dot(L,U))
print("Прилумаем вектор правых частей B и решим систему A*X = B:")
B = np.array([12,2,1])
print(B)
print("Решение системы:")
print(np.linalg.solve(A,B))

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
[[ -2. -12. -52.]
 [  3.  26.  70.]
 [ -1. -14. -18.]]
A = L*U
[[ 4. 28. 73.]
 [ 1.  2.  3.]
 [ 2. 16. 21.]]
Прилумаем вектор правых частей B и решим систему A*X = B:
[12  2  1]
Решение системы:
[15.81018519 -1.47453704 -0.28703704]
